/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSchemaRouteImport } from './routes/dashboard/schema'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard/playground'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardConfigureRouteImport } from './routes/dashboard/configure'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardInfrastructureIndexRouteImport } from './routes/dashboard/infrastructure/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchemaRoute = DashboardSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigureRoute = DashboardConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastructureIndexRoute =
  DashboardInfrastructureIndexRouteImport.update({
    id: '/infrastructure/',
    path: '/infrastructure/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/configure': typeof DashboardConfigureRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/schema': typeof DashboardSchemaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/configure': typeof DashboardConfigureRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/schema': typeof DashboardSchemaRoute
  '/dashboard': typeof DashboardIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/configure': typeof DashboardConfigureRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/schema': typeof DashboardSchemaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/dashboard/infrastructure/': typeof DashboardInfrastructureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/configure'
    | '/dashboard/logs'
    | '/dashboard/playground'
    | '/dashboard/schema'
    | '/dashboard/'
    | '/welcome'
    | '/dashboard/infrastructure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/configure'
    | '/dashboard/logs'
    | '/dashboard/playground'
    | '/dashboard/schema'
    | '/dashboard'
    | '/welcome'
    | '/dashboard/infrastructure'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/configure'
    | '/dashboard/logs'
    | '/dashboard/playground'
    | '/dashboard/schema'
    | '/dashboard/'
    | '/welcome/'
    | '/dashboard/infrastructure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schema': {
      id: '/dashboard/schema'
      path: '/schema'
      fullPath: '/dashboard/schema'
      preLoaderRoute: typeof DashboardSchemaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configure': {
      id: '/dashboard/configure'
      path: '/configure'
      fullPath: '/dashboard/configure'
      preLoaderRoute: typeof DashboardConfigureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/infrastructure/': {
      id: '/dashboard/infrastructure/'
      path: '/infrastructure'
      fullPath: '/dashboard/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardConfigureRoute: typeof DashboardConfigureRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardSchemaRoute: typeof DashboardSchemaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInfrastructureIndexRoute: typeof DashboardInfrastructureIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardConfigureRoute: DashboardConfigureRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardSchemaRoute: DashboardSchemaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInfrastructureIndexRoute: DashboardInfrastructureIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  WelcomeIndexRoute: WelcomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
